export class formFieldDescription{
	public formFieldDescriptionData = {
	store: 'Store',
      injuredPersonFullName:'Name of the injured',
      ageType:'',
      ageValue:'Age',
      appropriateAge: 'Age Approximate',
      injuredPersonContactNumber:'Contact Number (parent’s, if injured person is a child)',
      injuredPersonEmail:'Contact Email',
      injuredPersonAddress: 'Address',
      significantOthers:'Parent/Guardian/Responsible person',
      eventDate:'Incident Date',
      eventTime:'Time',
      approximateDate: 'Approximate',
      reportedDate: 'Reported Date ',
      reportedTime: 'Time',
      storeComments: 'Where in store',
      injurySustained: 'injury sustained',
      injuryCircumstances: 'Circumstances',
      productDescriptionView: '',
      productREcommentedAgeView: '',
      evidenceAvailable: 'CCTV/Photos',
      evidenceTakenBy: 'CCTV/Photos taken by',
      evidences: 'Drag & drop, or click to add evidence files',
      evidencesImportant: 'You must remove the files from your mobile device after uploading.',
      witnessAvailable:'Witness',
      witness:'Drag & drop, or click to add witness statement files',
      otherComments: 'Other Comments',
      priorityCode: 'Priority',
      csdNumber: 'CSD Tracking Number',
      complainant:'Complainant',
      productId: 'Product Description/ID',
      productDescription: '',
      recommendedAge: 'Recommended age',
      childRecommendedAge: 'Recommended age',
      batchNo: 'Batch number/Serial number',
      productReturnToStore: 'When returned to store',
      productReturnToHeadOffice: 'When returned to Head Office',
      productAge: 'Product Age',
      proofOfPurchaseFilePath: 'Attach a product receipt',
      problemReportedBefore: 'This problem has been reported before',
      faultCode: 'Nature of product faul',
      witnessName:'Witnesses name',
      witnessContactNumber:'Contact number',
      witnessEmail:'Contact email',
      witnessAddress:'Address',
      witnessStatement:'Witness statement',
      resolveActions: 'Incident prevention',
      goodWillGuster: 'Goodwill gesture',
      actionTakenToResolve:'',
      assigneeSearchValue: '',
      handlers: 'Assign Handler',
      initials: 'Initials',
      severity: 'Injury severity',
      preventability: 'Preventability',
      legalStatus: 'Legal status',
      claimReference: 'Claim reference',
      claimDate: 'Date of claim',
      cctvStatusCode: 'CCTV status',
      photoStatusCode: 'Photo Status',
      deleteDate: 'Deletion date',
      incidentCode: 'Incident code',
      actoinTakenComment:'Comments',
      productAgeType:'',
      followUpCall:'Follow-up call',
      noFootageAvailable:'No CCTV Available'
	}
}