export class TooltipMessage {
	public toolTipData:any={
store:'Select incident happen store',
injuredPersonFullName: "Full Name",
injuredParentContactNo: "Parent Conatct No",
injuredPersonContactNo: "Conatact No",
emailAddress: "Email Address",
actionTaken: "Resolve action",
address:"Address",
ageDropdown: "Select Age",
ageAppropriate: "Age is Appropriate",
significantOthers:"Enter significant name",
approximate:"Event date & time is Approximate",
batchNo: "batch No of product",
cctv: "CCTV",
cctvStatus:"CCTV Status",
circumstances: "Injury Circumstances",
claimReference: "claim reference",
complainant: "Enter the complainant name",
csdNumber: "CSD Number",
dateOfClaim: "Claim date",
eventDateTime: "Enter the actual date and time of the incident",
goodwillGesture: "Good Will",
incidentCode: "Incident Code",
incidentReporterName: "Reporter Name",
initial:"Enter your initials",
injurySeverity: "Injury Severity",
injurySustained: "Injury Sustained",
legalStatus: "Status of incident",
natureOfProductFault: "product fault nature",
photoStatus: "Photo Status",
photoTakenBy: "Photo taken by",
photos: "Photos",
preventability: "Preventability",
priority: "incident priority",
problemReportedBefore: "Problem occured before",
productAge: "please enter product age",
productCircumstances: "product circumstances",
productDescription: "product description",
productId: "please enter product ir or product description in search box and select corresponding incident againt product id or description",
productReturnToHeadOffice: "When Product returned to head office",
productReturnToStore: "When Product returned to store",
proofOfPurchase:"Please upload the proof of purchase",
recommendedAge: "recommended age to use product",
reportedDateTime:"Enter the reported date and time of the incident",
storeComments:"Enter Comments",
storeLocation:" Enter Store id",
whereInStore:"Store Location",
witnessAddress:"Witness Address",
witnessName:"Injury Witness Name",
witnessStatement:"Witness statement",
witnesscontactNumber:"Witness contact No",
witnessAvailable:"Please select if witness available or not",
witnesses:"add available witness details",
evidences:"If you have evidance name or photo or video add below details",
evidenceTakenByName:"please enter name whom taken evidance ",
otherComments:"please provide if any ther comments you have",
handlingTeam:"if you have any other team handle this incident please search name and select it ",
deletionDate:"date of incident deletion"
};
}
